version: '2.1'
services:
  web:
    extends:
      file: ../common-services.yml
      service: web
    volumes:
      - "../../:/pycroft"
    # A service being extended may have no links.
    links:
      - db:db
      - dummy_worker:dummy_worker
      - rabbitmq:rabbitmq
    ports:
      - 5001:5000
  dummy_worker:
    extends:
      file: ../common-services.yml
      service: dummy_worker
    volumes:
      - "../../:/pycroft"
    links:
      - rabbitmq:rabbitmq
  db:
    extends:
      file: ../common-services.yml
      service: db
    volumes:
      - "pycroft_postgres:/var/lib/postgresql/data"
      - "../../:/pycroft"
    ports:
      - 55432:5432
  rabbitmq:
    extends:
      file: ../common-services.yml
      service: rabbitmq

volumes:
  pycroft_postgres:
