version: '2.1'
services:
  web:
    extends:
      file: ../common-services.yml
      service: web_testing
    volumes:
      - "../../:/pycroft"
    links:
      - db:db
      - ldap:ldap
      - rabbitmq:rabbitmq
  dummy_worker:
    extends:
      file: ../common-services.yml
      service: dummy_worker
    volumes:
      - "../../:/pycroft"
    links:
      - rabbitmq:rabbitmq
  db:
    extends:
      file: ../common-services.yml
      service: db_optimized
  ldap:
    extends:
      file: ../common-services.yml
      service: ldap
  rabbitmq:
    extends:
      file: ../common-services.yml
      service: rabbitmq
