# This file is a workaround for a bug in docker-compose.  Once you use
# `extends` to extend from another file, you cannot use `extend`
# referencing to that same file anymore.  You must introduce another
# file.
# Also, these services have been suffixed `_base` to avoid name
# conflicts which trigger another bug.
# See https://github.com/lukasjuhrich/docker-compose-extends/ for some
# exploration of the behavior.
version: '2.1'
services:
  web_base:
    build:
      context: ..
      # docker-compose can automatically use variables from the environment.
      # UID is set by bash, but not exported. Zsh also sets GID, but doesn't
      # export them either.
      # Add export UID; export GID; to your zsh config
      # Add export UID; export GID="$(id -g)" to your bash config
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    image: pycroft  # tag of the built image
    environment:
      - PYCROFT_DB_URI=postgresql://postgres:password@db:5432/pycroft
      - HADES_CELERY_APP_NAME=dummy_tasks
      - HADES_BROKER_URI=amqp://celery:celery@rabbitmq:5672/
      - HADES_RESULT_BACKEND_URI=rpc://celery:celery@rabbitmq:5672/
    command: "pycroft --debug --exposed --profile"
  db_base:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pycroft
